# Generated by Django 3.2.9 on 2021-11-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('age', models.IntegerField(default='0')),
                ('exact', models.BooleanField(default=True)),
            ],
        ),
    ]
